### ISSUE TITLE
my pc goes brr

### ISSUE THREAD

**Issue by sugisaru** [NikV2/PredictionEverything#8]
i just added this plugin to my localhost server and my pc just started to burn. welp

**Comment by EcstasyCode** [comment]
oh nu.

**Comment by NikV2** [comment]
It's a config issue, you have to purchase the enterprise version of verus.

**Comment by ed0cinU** [comment]
xd

**Comment by sugisaru** [comment]
got it running, closing the issue now.
thank you for this masterpiece! uwu
